export const FETCH_RESTAURANTS_START = 'FETCH_RESTAURANTS_START'
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS'
export const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE'

export const LOGIN_USER_START = 'LOGIN_USER_START'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const REGISTER_USER_START = 'REGISTER_USER_START'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const FETCH_MENU_START = 'FETCH_MENU_START'
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS'
export const FETCH_MENU_FAILURE = 'FETCH_MENU_FAILURE'

export const LOG_OUT_USER_SUCCESS = 'LOG_OUT_USER_SUCCESS'

export const ADD_MENU_ITEM_TO_BASKET = "ADD_MENU_ITEM_TO_CART"
export const REMOVE_MENU_ITEM_FROM_BASKET = "REMOVE_MENU_ITEM_FROM_BASKET"

export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START"
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS"
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE"

export const PLACE_ORDER_START = "PLACE_ORDER_START"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE"

export const ADD_FILTER_SUCCESS = "ADD_FILTER_SUCCESS"
export const REMOVE_FILTER_SUCCESS = "REMOVE_FILTER_SUCCESS"
